package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'AggBuild1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("AggBuild1")
    name = "Agg build 1"

    type = BuildTypeSettings.Type.COMPOSITE

    vcs {
        root(DslContext.settingsRoot)

        showDependenciesChanges = true
    }

    triggers {
        vcs {
        }
    }

    dependencies {
        snapshot(AbsoluteId("ReconNg_Agg")) {
        }
        snapshot(RelativeId("Build1")) {
        }
        snapshot(RelativeId("Build2")) {
        }
    }
}))

